name: 'SagonWeb_CI' #set whatevername you want to your github job
 # set the events you would like to trigger this job
on:
  push:
    branches: 
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0  # use the latest version of the action
        with:
          email: ${{ 'king.kemsty@gmail.com' }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: ${{ 'sagonweb' }} # you aplication name
          dockerfile: '.' # set the path to the folder wher the Dokerfile is located
